services:
  - type: web
    name: smartcaptcha-backend
    env: python
    rootDir: smartcaptcha/backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
